/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmanmain;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Nick
 */
public class TheWindow extends javax.swing.JFrame {

    private String word;
    private int score;
    private JTextField[] jtf;
    private JPanel[] lines;
    private JPanel[] theHangMan;
    private int z;
    
    /**
     * Creates new form TheWindow
     */
    public TheWindow() {
       jtf = new JTextField[8];
       lines = new JPanel[8];
       theHangMan = new JPanel[6];
       z = 0;
        initComponents();
        
    }
    
    public void randomWord()
    {
        Random r = new Random();
        String[] wordList = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        
        word = wordList[r.nextInt(4)];
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        highscores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        credits = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        hangmanGame = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        rightArm = new javax.swing.JPanel();
        leftArm = new javax.swing.JPanel();
        leftLeg = new javax.swing.JPanel();
        rightLeg = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        l8 = new javax.swing.JPanel();
        l1 = new javax.swing.JPanel();
        l3 = new javax.swing.JPanel();
        l4 = new javax.swing.JPanel();
        l5 = new javax.swing.JPanel();
        l2 = new javax.swing.JPanel();
        l7 = new javax.swing.JPanel();
        l6 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        endPage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Highscores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Credits");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(77, 77, 77))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(67, 67, 67))
        );

        mainPanel.add(menu, "card2");

        highscores.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Highscores");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField10.setText("jTextField10");

        javax.swing.GroupLayout highscoresLayout = new javax.swing.GroupLayout(highscores);
        highscores.setLayout(highscoresLayout);
        highscoresLayout.setHorizontalGroup(
            highscoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(highscoresLayout.createSequentialGroup()
                .addGroup(highscoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(highscoresLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton4))
                    .addGroup(highscoresLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(highscoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        highscoresLayout.setVerticalGroup(
            highscoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(highscoresLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(78, 78, 78))
        );

        mainPanel.add(highscores, "card3");

        credits.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel2.setBackground(new java.awt.Color(255, 51, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Credits");

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creditsLayout = new javax.swing.GroupLayout(credits);
        credits.setLayout(creditsLayout);
        creditsLayout.setHorizontalGroup(
            creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsLayout.createSequentialGroup()
                .addGroup(creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditsLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(creditsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton5)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        creditsLayout.setVerticalGroup(
            creditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(82, 82, 82))
        );

        mainPanel.add(credits, "card4");

        hangmanGame.setBackground(new java.awt.Color(204, 204, 204));
        hangmanGame.setPreferredSize(new java.awt.Dimension(600, 400));
        playTheGame();
        hangmanGame.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Hangman");
        hangmanGame.add(jLabel3);
        jLabel3.setBounds(12, 13, 127, 29);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setBorder(null);
        hangmanGame.add(jTextField1);
        jTextField1.setBounds(88, 210, 40, 36);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setBorder(null);
        hangmanGame.add(jTextField2);
        jTextField2.setBounds(140, 210, 40, 36);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setBorder(null);
        hangmanGame.add(jTextField3);
        jTextField3.setBounds(190, 210, 40, 36);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField4.setBorder(null);
        hangmanGame.add(jTextField4);
        jTextField4.setBounds(240, 210, 40, 36);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField5.setBorder(null);
        hangmanGame.add(jTextField5);
        jTextField5.setBounds(290, 210, 40, 36);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField6.setBorder(null);
        hangmanGame.add(jTextField6);
        jTextField6.setBounds(350, 210, 40, 36);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField7.setBorder(null);
        hangmanGame.add(jTextField7);
        jTextField7.setBounds(400, 210, 40, 36);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField8.setBorder(null);
        hangmanGame.add(jTextField8);
        jTextField8.setBounds(450, 210, 40, 36);

        jLabel4.setText("Score");
        hangmanGame.add(jLabel4);
        jLabel4.setBounds(12, 104, 53, 24);

        jTextField9.setText("100");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        hangmanGame.add(jTextField9);
        jTextField9.setBounds(12, 135, 34, 22);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setText("A");
        jButton6.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton6.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton6);
        jButton6.setBounds(7, 264, 40, 32);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setText("B");
        jButton7.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton7.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton7);
        jButton7.setBounds(54, 264, 40, 32);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton8.setText("C");
        jButton8.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton8.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton8);
        jButton8.setBounds(101, 264, 40, 32);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton9.setText("D");
        jButton9.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton9.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton9);
        jButton9.setBounds(148, 264, 40, 32);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton10.setText("E");
        jButton10.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton10.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton10);
        jButton10.setBounds(195, 264, 40, 32);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton11.setText("F");
        jButton11.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton11.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton11);
        jButton11.setBounds(242, 264, 40, 32);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton12.setText("G");
        jButton12.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton12.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton12);
        jButton12.setBounds(289, 264, 40, 32);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton13.setText("H");
        jButton13.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton13.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton13);
        jButton13.setBounds(336, 264, 40, 32);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton14.setText("I");
        jButton14.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton14.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton14);
        jButton14.setBounds(383, 264, 40, 32);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton15.setText("J");
        jButton15.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton15.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton15);
        jButton15.setBounds(430, 264, 40, 32);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton16.setText("K");
        jButton16.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton16.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton16);
        jButton16.setBounds(477, 264, 40, 32);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton17.setText("L");
        jButton17.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton17.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton17);
        jButton17.setBounds(524, 264, 40, 32);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton18.setText("M");
        jButton18.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton18.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton18);
        jButton18.setBounds(571, 264, 40, 32);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton19.setText("N");
        jButton19.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton19.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton19);
        jButton19.setBounds(7, 303, 40, 32);

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton20.setText("O");
        jButton20.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton20.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton20);
        jButton20.setBounds(54, 303, 40, 32);

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton21.setText("P");
        jButton21.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton21.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton21);
        jButton21.setBounds(101, 303, 40, 32);

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton22.setText("Q");
        jButton22.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton22.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton22);
        jButton22.setBounds(148, 303, 40, 32);

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton23.setText("R");
        jButton23.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton23.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton23);
        jButton23.setBounds(195, 303, 40, 32);

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton24.setText("S");
        jButton24.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton24.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton24);
        jButton24.setBounds(242, 303, 40, 32);

        jButton25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton25.setText("T");
        jButton25.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton25.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton25);
        jButton25.setBounds(289, 303, 40, 32);

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton26.setText("U");
        jButton26.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton26.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton26);
        jButton26.setBounds(336, 303, 40, 32);

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton27.setText("V");
        jButton27.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton27.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton27);
        jButton27.setBounds(383, 303, 40, 32);

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButton28.setText("W");
        jButton28.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton28.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton28);
        jButton28.setBounds(430, 303, 40, 32);

        jButton29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton29.setText("X");
        jButton29.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton29.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton29);
        jButton29.setBounds(477, 303, 40, 32);

        jButton30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton30.setText("Y");
        jButton30.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton30.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton30);
        jButton30.setBounds(524, 303, 40, 32);

        jButton31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton31.setText("Z");
        jButton31.setMaximumSize(new java.awt.Dimension(10, 10));
        jButton31.setPreferredSize(new java.awt.Dimension(30, 20));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton31);
        jButton31.setBounds(571, 303, 40, 32);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        hangmanGame.add(jPanel3);
        jPanel3.setBounds(290, 22, 8, 170);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        hangmanGame.add(jPanel4);
        jPanel4.setBounds(290, 20, 61, 8);

        head.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        hangmanGame.add(head);
        head.setBounds(340, 60, 30, 30);

        body.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        hangmanGame.add(body);
        body.setBounds(350, 90, 8, 50);

        rightArm.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout rightArmLayout = new javax.swing.GroupLayout(rightArm);
        rightArm.setLayout(rightArmLayout);
        rightArmLayout.setHorizontalGroup(
            rightArmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rightArmLayout.setVerticalGroup(
            rightArmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        hangmanGame.add(rightArm);
        rightArm.setBounds(320, 100, 30, 9);

        leftArm.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout leftArmLayout = new javax.swing.GroupLayout(leftArm);
        leftArm.setLayout(leftArmLayout);
        leftArmLayout.setHorizontalGroup(
            leftArmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        leftArmLayout.setVerticalGroup(
            leftArmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        hangmanGame.add(leftArm);
        leftArm.setBounds(350, 100, 40, 9);

        leftLeg.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout leftLegLayout = new javax.swing.GroupLayout(leftLeg);
        leftLeg.setLayout(leftLegLayout);
        leftLegLayout.setHorizontalGroup(
            leftLegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        leftLegLayout.setVerticalGroup(
            leftLegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        hangmanGame.add(leftLeg);
        leftLeg.setBounds(320, 130, 30, 9);

        rightLeg.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout rightLegLayout = new javax.swing.GroupLayout(rightLeg);
        rightLeg.setLayout(rightLegLayout);
        rightLegLayout.setHorizontalGroup(
            rightLegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        rightLegLayout.setVerticalGroup(
            rightLegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        hangmanGame.add(rightLeg);
        rightLeg.setBounds(350, 130, 40, 9);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        hangmanGame.add(jPanel8);
        jPanel8.setBounds(350, 20, 8, 40);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        hangmanGame.add(jPanel9);
        jPanel9.setBounds(140, 183, 329, 9);

        l8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l8Layout = new javax.swing.GroupLayout(l8);
        l8.setLayout(l8Layout);
        l8Layout.setHorizontalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l8Layout.setVerticalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l8);
        l8.setBounds(450, 250, 40, 10);

        l1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l1Layout = new javax.swing.GroupLayout(l1);
        l1.setLayout(l1Layout);
        l1Layout.setHorizontalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l1Layout.setVerticalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l1);
        l1.setBounds(90, 250, 40, 10);

        l3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l3Layout = new javax.swing.GroupLayout(l3);
        l3.setLayout(l3Layout);
        l3Layout.setHorizontalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l3Layout.setVerticalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l3);
        l3.setBounds(190, 250, 40, 10);

        l4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l4Layout = new javax.swing.GroupLayout(l4);
        l4.setLayout(l4Layout);
        l4Layout.setHorizontalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l4Layout.setVerticalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l4);
        l4.setBounds(240, 250, 40, 10);

        l5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l5Layout = new javax.swing.GroupLayout(l5);
        l5.setLayout(l5Layout);
        l5Layout.setHorizontalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l5Layout.setVerticalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l5);
        l5.setBounds(290, 250, 40, 10);

        l2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l2Layout = new javax.swing.GroupLayout(l2);
        l2.setLayout(l2Layout);
        l2Layout.setHorizontalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l2Layout.setVerticalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l2);
        l2.setBounds(140, 250, 40, 10);

        l7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l7Layout = new javax.swing.GroupLayout(l7);
        l7.setLayout(l7Layout);
        l7Layout.setHorizontalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l7Layout.setVerticalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l7);
        l7.setBounds(400, 250, 40, 10);

        l6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout l6Layout = new javax.swing.GroupLayout(l6);
        l6.setLayout(l6Layout);
        l6Layout.setHorizontalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        l6Layout.setVerticalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        hangmanGame.add(l6);
        l6.setBounds(350, 250, 40, 10);

        jButton32.setText("Skip");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        hangmanGame.add(jButton32);
        jButton32.setBounds(500, 70, 57, 25);

        mainPanel.add(hangmanGame, "card5");

        endPage.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel5.setText("Score");

        javax.swing.GroupLayout endPageLayout = new javax.swing.GroupLayout(endPage);
        endPage.setLayout(endPageLayout);
        endPageLayout.setHorizontalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        endPageLayout.setVerticalGroup(
            endPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPageLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        mainPanel.add(endPage, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        menu.setVisible(true);
        highscores.setVisible(false);
        credits.setVisible(false);
        hangmanGame.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(false);
        highscores.setVisible(true);
        credits.setVisible(false);
        hangmanGame.setVisible(false);
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
        menu.setVisible(false);
        highscores.setVisible(false);
        credits.setVisible(true);
        hangmanGame.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        highscores.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(false);
        highscores.setVisible(false);
        credits.setVisible(false);
        hangmanGame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isGameOver()
    {
        boolean over = false;
        if(score < 59)
        {
            over = true;
            
        }
        else
            over = false;
        return over;
        
    }
    
    public void hideMan()
    {
        head.setVisible(false);
        body.setVisible(false);
        leftArm.setVisible(false);
        rightArm.setVisible(false);
        leftLeg.setVisible(false);
        rightLeg.setVisible(false);
        
        theHangMan[0]=head;
        theHangMan[1]=body;
        theHangMan[2]=leftArm;
        theHangMan[3]=rightArm;
        theHangMan[4]=leftLeg;
        theHangMan[5]=rightLeg;
        
        
    }
    
    public void lines()
    {
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        
        lines[0] = l1;
        lines[1] = l2;
        lines[2] = l3;
        lines[3] = l4;
        lines[4] = l5;
        lines[5] = l6;
        lines[6] = l7;
        lines[7] = l8;
        
    }
    public void showMan()
    {
        
        theHangMan[z].setVisible(true);
        z++;
    }
    
    public void playTheGame()
    {
       
         setTextField();
         lines();
         hideMan();
        score = 100;
        randomWord();
        System.out.print(word);
        for(int i = 0;i < word.length(); i++)
        {
            jtf[i].setVisible(true);
            lines[i].setVisible(true);
        }
       
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('a' == check[i])
            {
                //set letter
                jtf[i].setText("A");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {
           score -= 10;
           showMan();
           //hangman part
        }
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
         
      
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('b' == check[i])
            {
                //set letter
                jtf[i].setText("B");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('c' == check[i])
            {
                //set letter
                jtf[i].setText("C");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           showMan();
        }
           //hangman part
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('d' == check[i])
            {
                //set letter
                jtf[i].setText("D");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('e' == check[i])
            {
                //set letter
                jtf[i].setText("E");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('f' == check[i])
            {
                //set letter
                jtf[i].setText("F");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('g' == check[i])
            {
                //set letter
                jtf[i].setText("G");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('h' == check[i])
            {
                //set letter
                jtf[i].setText("H");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('i' == check[i])
            {
                //set letter
                jtf[i].setText("I");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('j' == check[i])
            {
                //set letter
                jtf[i].setText("J");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('k' == check[i])
            {
                //set letter
                jtf[i].setText("K");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('l' == check[i])
            {
                //set letter
                jtf[i].setText("L");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('m' == check[i])
            {
                //set letter
                jtf[i].setText("M");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('n' == check[i])
            {
                //set letter
                jtf[i].setText("N");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('o' == check[i])
            {
                //set letter
                jtf[i].setText("O");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('p' == check[i])
            {
                //set letter
                jtf[i].setText("P");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('q' == check[i])
            {
                //set letter
                jtf[i].setText("Q");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('r' == check[i])
            {
                //set letter
                jtf[i].setText("R");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('s' == check[i])
            {
                //set letter
                jtf[i].setText("S");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('t' == check[i])
            {
                //set letter
                jtf[i].setText("T");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('u' == check[i])
            {
                //set letter
                jtf[i].setText("U");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('v' == check[i])
            {
                //set letter
                jtf[i].setText("V");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('w' == check[i])
            {
                //set letter
                jtf[i].setText("W");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('x' == check[i])
            {
                //set letter
                jtf[i].setText("X");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('y' == check[i])
            {
                //set letter
                jtf[i].setText("Y");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        {  score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
         char[] check = word.toCharArray();
        
        int letterCount = 0;
        for(int i = 0; i < check.length;i++){
            if('z' == check[i])
            {
                //set letter
                jtf[i].setText("Z");
                letterCount++;
            } 
        }
        if(letterCount == 0)
        { score -= 10;
           //hangman part
           showMan();
        }
        
        if(isGameOver()){
            //end game
        }
        jTextField9.setText(new Integer(score).toString());
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(false);
        highscores.setVisible(false);
        credits.setVisible(false);
        hangmanGame.setVisible(false);
        endPage.setVisible(true);
    }//GEN-LAST:event_jButton32ActionPerformed

    public void setTextField()
    {
        
         jTextField1.setVisible(false);
         jTextField2.setVisible(false);
         jTextField3.setVisible(false);
         jTextField4.setVisible(false);
         
         jTextField5.setVisible(false);
         jTextField6.setVisible(false);
         jTextField7.setVisible(false);
         jTextField8.setVisible(false);
         
         jtf[0] = jTextField1;
         jtf[1] = jTextField2;
         jtf[2] = jTextField3;
         jtf[3] = jTextField4;
         jtf[4] = jTextField5;
         jtf[5] = jTextField6;
         jtf[6] = jTextField7;
         jtf[7] = jTextField8;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel credits;
    private javax.swing.JPanel endPage;
    private javax.swing.JPanel hangmanGame;
    private javax.swing.JPanel head;
    private javax.swing.JPanel highscores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel l1;
    private javax.swing.JPanel l2;
    private javax.swing.JPanel l3;
    private javax.swing.JPanel l4;
    private javax.swing.JPanel l5;
    private javax.swing.JPanel l6;
    private javax.swing.JPanel l7;
    private javax.swing.JPanel l8;
    private javax.swing.JPanel leftArm;
    private javax.swing.JPanel leftLeg;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel rightArm;
    private javax.swing.JPanel rightLeg;
    // End of variables declaration//GEN-END:variables
}
